# Production Properties

# Database
spring.datasource.url=${AWS_RDS_POSTGRESQL_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logs
logging.file.name=logs/roadmate.log
logging.level.com.roadmateserver.root.service.impl=INFO

# Actuator
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*

# Caching
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=6379
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true
spring.data.redis.connect-timeout=10000
spring.data.redis.timeout=10000