# Production Properties

# Database
spring.datasource.url=${AWS_MYSQL_URL}
spring.datasource.username=${AWS_MYSQL_USERNAME}
spring.datasource.password=${AWS_MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Logs
logging.file.name=logs/roadmate.log
logging.level.com.roadmateserver.root.service.impl=INFO

# Actuator
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*

# Caching
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.username=default
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.connect-timeout=10000
spring.data.redis.timeout=10000