# Development Properties

# Database for MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/roadmate_dev
spring.datasource.username=root
spring.datasource.password=sql2025#zinD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# debugging
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

# Logs
logging.file.name=logs/roadmate.log
logging.level.com.roadmateserver.root.service.impl=DEBUG

# Actuator
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*

# Caching
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
server.port=8080