spring.application.name=roadmate-server
server.servlet.context-path=/api/v1
server.port=${PORT:8080}
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
clerk.jwks.url=${CLERK_JWKS_URL}
clerk.api.key=${CLERK_API_KEY}

spring.profiles.active=dev
