# Common
spring.application.name=roadmate-server
server.servlet.context-path=/api/v1
server.port=${PORT:8080}

# Stripe API Key
stripe.secret.key=${STRIPE_SECRET_KEY}

# Clerk API Keys
clerk.jwks.url=${CLERK_JWKS_URL}
clerk.api.key=${CLERK_API_KEY}
clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

# AWS S3 Configuration
aws.s3.bucket-name=${S3_BUCKET_NAME}
aws.region=${AWS_REGION}
aws.access-key=${AWS_ACCESS_KEY_ID}
aws.secret-key=${AWS_SECRET_ACCESS_KEY}

# profile active
spring.profiles.active=dev

# Max file size
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
